## NOTE: THIS FILE IS GENERATED BY EPSCRIPT! DO NOT MODITY
from eudplib import *
from eudplib.epscript.helper import _RELIMP, _IGVA, _CGFW, _ARR, _VARR, _SRET, _SV, _ATTW, _ARRW, _ATTC, _ARRC, _L2V, _LVAR, _LSH
# (Line 1) function onPluginStart() { // This function will be executed once when the game starts
@EUDFunc
def onPluginStart():
    # (Line 2) DisplayTextAll("Hello World");
    # (Line 3) }
    f_setcurpl2cpcache([], DisplayTextAll("Hello World"))
    # (Line 5) function beforeTriggerExec() { // This function will be executed once each frame before classical triggers

@EUDFunc
def beforeTriggerExec():
    # (Line 6) }
    # (Line 8) function afterTriggerExec() { // This function will be executed once per frame after classical triggers
    pass

@EUDFunc
def afterTriggerExec():
    # (Line 10) }
    pass
